# schemas/equipment_class.py
EquipmentClass = {
    "Rotating Equipment": [
        {"code": "PUMP_CENT", "description": "Centrifugal Pump"},
        {"code": "PUMP_POS", "description": "Positive Displacement Pump"},
        {"code": "PUMP_GEAR", "description": "Gear Pump"},
        {"code": "PUMP_DIA", "description": "Diaphragm Pump"},
        {"code": "PUMP_SCREW", "description": "Screw Pump"},
        {"code": "PUMP_LOBE", "description": "Lobe Pump"},
        {"code": "PUMP_PER", "description": "Peristaltic Pump"},
        {"code": "PUMP_VAC", "description": "Vacuum Pump"},
        {"code": "COMP_REC", "description": "Reciprocating Compressor"},
        {"code": "COMP_CENT", "description": "Centrifugal Compressor"},
        {"code": "COMP_AXI", "description": "Axial Compressor"},
        {"code": "COMP_SCREW", "description": "Screw Compressor"},
        {"code": "COMP_ROOT", "description": "Roots Blower"},
        {"code": "TURB_GAS", "description": "Gas Turbine"},
        {"code": "TURB_STM", "description": "Steam Turbine"},
        {"code": "TURB_HYD", "description": "Hydraulic Turbine"},
        {"code": "MOT_AC", "description": "AC Induction Motor"},
        {"code": "MOT_DC", "description": "DC Motor"},
        {"code": "MOT_SYN", "description": "Synchronous Motor"},
        {"code": "MOT_SER", "description": "Servo Motor"},
        {"code": "FAN_AXI", "description": "Axial Fan"},
        {"code": "FAN_CENT", "description": "Centrifugal Fan"},
        {"code": "FAN_ROOF", "description": "Roof Ventilator"},
        {"code": "FAN_BLOW", "description": "Blower"},
        {"code": "AGIT_PROP", "description": "Propeller Mixer"},
        {"code": "AGIT_TURB", "description": "Turbine Mixer"},
        {"code": "AGIT_PADD", "description": "Paddle Mixer"},
        {"code": "GEAR_SPUR", "description": "Spur Gearbox"},
        {"code": "GEAR_HEL", "description": "Helical Gearbox"},
        {"code": "GEAR_WORM", "description": "Worm Gearbox"},
        {"code": "GEAR_PLAN", "description": "Planetary Gearbox"}
    ],
    "Static Equipment": [
        {"code": "VES_SEP", "description": "Separator Vessel"},
        {"code": "VES_DRUM", "description": "Drum"},
        {"code": "VES_ACC", "description": "Accumulator"},
        {"code": "VES_SUR", "description": "Surge Vessel"},
        {"code": "HEX_ST", "description": "Shell and Tube Heat Exchanger"},
        {"code": "HEX_PLT", "description": "Plate Heat Exchanger"},
        {"code": "HEX_AIR", "description": "Air-Cooled Heat Exchanger"},
        {"code": "HEX_SPR", "description": "Spiral Heat Exchanger"},
        {"code": "BOIL_STM", "description": "Steam Boiler"},
        {"code": "BOIL_HW", "description": "Hot Water Boiler"},
        {"code": "FURN_IND", "description": "Industrial Furnace"},
        {"code": "TANK_ATM", "description": "Atmospheric Tank"},
        {"code": "TANK_PRES", "description": "Pressurized Tank"},
        {"code": "TANK_CRYO", "description": "Cryogenic Tank"},
        {"code": "COL_DIST", "description": "Distillation Column"},
        {"code": "COL_ABS", "description": "Absorber"},
        {"code": "COL_REAC", "description": "Reactor"},
        {"code": "FILT_MECH", "description": "Mechanical Filter"},
        {"code": "FILT_CART", "description": "Cartridge Filter"},
        {"code": "FILT_BAG", "description": "Bag Filter"},
        {"code": "SEP_CYC", "description": "Cyclone Separator"},
        {"code": "STR_BASE", "description": "Base Frame"},
        {"code": "STR_SUP", "description": "Support Structure"},
        {"code": "STR_SKID", "description": "Equipment Skid"}
    ],
    "Electrical Equipment": [
        {"code": "TRF_DIST", "description": "Distribution Transformer"},
        {"code": "TRF_POW", "description": "Power Transformer"},
        {"code": "TRF_INS", "description": "Instrument Transformer"},
        {"code": "SWG_LV", "description": "Low Voltage Switchgear"},
        {"code": "SWG_MV", "description": "Medium Voltage Switchgear"},
        {"code": "SWG_HV", "description": "High Voltage Switchgear"},
        {"code": "GEN_DIE", "description": "Diesel Generator"},
        {"code": "GEN_GAS", "description": "Gas Generator"},
        {"code": "GEN_STM", "description": "Steam Turbine Generator"},
        {"code": "CAB_LV", "description": "Low Voltage Cable"},
        {"code": "CAB_MV", "description": "Medium Voltage Cable"},
        {"code": "CAB_HV", "description": "High Voltage Cable"},
        {"code": "MCC_FIX", "description": "Fixed Type MCC"},
        {"code": "MCC_WDR", "description": "Withdrawable Type MCC"},
        {"code": "INV_VFD", "description": "Variable Frequency Drive"},
        {"code": "INV_DCAC", "description": "DC/AC Inverter"},
        {"code": "UPS_ONL", "description": "Online UPS"},
        {"code": "UPS_OFF", "description": "Offline UPS"},
        {"code": "UPS_BAT", "description": "Battery Bank"},
        {"code": "LIG_SYS", "description": "Lighting System"}
    ],
    "Control Systems": [
        {"code": "DCS_MAIN", "description": "Main DCS System"},
        {"code": "DCS_LOC", "description": "Local DCS Node"},
        {"code": "PLC_STAND", "description": "Standalone PLC"},
        {"code": "PLC_RED", "description": "Redundant PLC"},
        {"code": "SCADA_SYS", "description": "SCADA System"},
        {"code": "HMI_STAND", "description": "Standalone HMI"},
        {"code": "HMI_MULTI", "description": "Multi-screen Console"},
        {"code": "CONT_PID", "description": "PID Controller"},
        {"code": "CONT_LOC", "description": "Local Control Panel"},
        {"code": "NET_ETH", "description": "Ethernet Network"},
        {"code": "NET_FBUS", "description": "Fieldbus Network"},
        {"code": "NET_PBUS", "description": "PROFIBUS Network"}
    ],
    "Instrumentation": [
        {"code": "SENS_PRES", "description": "Pressure Sensor"},
        {"code": "SENS_TEMP", "description": "Temperature Sensor"},
        {"code": "SENS_VIB", "description": "Vibration Sensor"},
        {"code": "SENS_FLOW", "description": "Flow Sensor"},
        {"code": "TRM_PRES", "description": "Pressure Transmitter"},
        {"code": "TRM_TEMP", "description": "Temperature Transmitter"},
        {"code": "TRM_LVL", "description": "Level Transmitter"},
        {"code": "ANL_GAS", "description": "Gas Analyzer"},
        {"code": "ANL_LIQ", "description": "Liquid Analyzer"},
        {"code": "ANL_PART", "description": "Particulate Analyzer"},
        {"code": "PG_GAUGE", "description": "Pressure Gauge"},
        {"code": "PG_SW", "description": "Pressure Switch"},
        {"code": "CV_GLOB", "description": "Globe Control Valve"},
        {"code": "CV_BALL", "description": "Ball Control Valve"},
        {"code": "CV_BUTT", "description": "Butterfly Control Valve"}
    ],
    "Piping Systems": [
        {"code": "PIPE_CS", "description": "Carbon Steel Pipe"},
        {"code": "PIPE_SS", "description": "Stainless Steel Pipe"},
        {"code": "PIPE_HDPE", "description": "HDPE Pipe"},
        {"code": "VAL_GATE", "description": "Gate Valve"},
        {"code": "VAL_GLOBE", "description": "Globe Valve"},
        {"code": "VAL_BALL", "description": "Ball Valve"},
        {"code": "VAL_CHECK", "description": "Check Valve"},
        {"code": "FIT_ELB", "description": "Elbow Fitting"},
        {"code": "FIT_TEE", "description": "Tee Fitting"},
        {"code": "FIT_RED", "description": "Reducer Fitting"},
        {"code": "FLG_ST", "description": "Standard Flange"},
        {"code": "FLG_BLND", "description": "Blind Flange"},
        {"code": "JNT_GSK", "description": "Gasket Joint"},
        {"code": "JNT_EXP", "description": "Expansion Joint"},
        {"code": "SUP_HANG", "description": "Pipe Hanger"},
        {"code": "SUP_CLAMP", "description": "Pipe Clamp"}
    ],
    "Miscellaneous Equipment": [
        {"code": "HVAC_SYS", "description": "HVAC System"},
        {"code": "FIRE_SYS", "description": "Fire Protection System"},
        {"code": "SAFE_EQP", "description": "Safety Equipment"},
        {"code": "LIFT_CRN", "description": "Crane"},
        {"code": "LIFT_HOIST", "description": "Hoist"},
        {"code": "WTR_TREAT", "description": "Water Treatment System"},
        {"code": "AIR_COMP", "description": "Compressed Air System"},
        {"code": "FUEL_HAND", "description": "Fuel Handling System"}
    ]
}